# Generated by Django 5.2 on 2025-07-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.DeleteModel(
            name='Slidebar',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'teacher'), (3, 'student')]),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
